name: default

kind: pipeline
type: docker

steps:
- name: backend
  image: golang:1.12-alpine
  commands:
    - go get
    - go build
    - go test
    - echo "done"

trigger:
  branch: 
  - master
  event:
  - push
